<?php

/**
 * @file
 * Contains invoice_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function invoice_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the invoice_field module.
    case 'help.page.invoice_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates the invoice number based on settings.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function invoice_field_theme() {
  return [
    'invoice_field' => [
      'template' => 'invoice_field',
      'render element' => 'children',
    ],
  ];
}
